name: Build and Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/
          
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: login to jfrog
      uses: jfrog/setup-jfrog-cli@v2
      env:
        ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
    - run: |
       jfrog --version
       jfrog rt c
       jfrog rt c show
       jfrog rt go-publish
       jfrog rt u "public/" default-npm-local
       
