name: Build and Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/ 
      - name: login to jfrog
        uses: jfrog/setup-jfrog-cli@v2
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
      - run: |
          npm config set registry https://devopslv.jfrog.io/artifactory/api/npm/default-npm-virtual/
          jfrog config add artifact --url=https://devopslv.jfrog.io/artifactory/api/npm/default-npm-virtual/
          jfrog rt u "public/" default-npm-remote
 
